name: Build and Push API Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code and setup Docker
        uses: actions/checkout@v3

      - name: Login and Set up Docker Buildx
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        continue-on-error: false # Ensure we stop if login fails

      - uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract metadata and Build & Push Docker image
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: vontainment/v-gpt-qdrant-api
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha,priority=100
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            typeâ¬¤
